### ISSUE TITLE
Formatter will break code with << and scientific notiation

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot-vscode-plugin#653]
### Godot version

4.2.2

### VS Code version

1.88.1

### Godot Tools VS Code extension version

2.0.0

### System information

Windows 10

### Issue description

The formatter will always add a space beteween `<<` resulting in `< <` which is not a valid operator.
It will also add a space after the 'e' in scientific notation. eg `1e-1` will result in `1e -1` which is also not valid.

### Steps to reproduce

Use bitshifts or scientific notation in a script and save with the plugin enabled.

**Comment by DaelonSuzuka** [comment]
This should already be fixed in #605.

**Comment by cjmaxik** [comment]
It is not fixed, unfortunately

![image](https://github.com/godotengine/godot-vscode-plugin/assets/1501705/40716cd5-b8de-422a-a236-8e3205d0a9f1)

**Comment by DaelonSuzuka** [comment]
@cjmaxik #605 hasn't been merged yet.

**Comment by DaelonSuzuka** [comment]
Formatting `<<` was fixed a while ago, and scientific notation _should_ be fixed in the next release.
