### ISSUE TITLE
Incorrect formatting for negative indices/keys

### ISSUE THREAD

**Issue by theXYZT** [godotengine/godot-vscode-plugin#889]
### Godot version

4.4.1

### VS Code version

1.102.2

### Godot Tools VS Code extension version

2.5.1

### System information

Windows 11

### Issue description

Negative indices are not formatted correctly in certain situations. For example, `x[-1]` gets formatted to `x[ - 1]`.

### Steps to reproduce

The following code

```
some_array[-1] = 0
print(some_array[-1])
```
formats to
```
some_array[-1] = 0
print(some_array[ - 1])
```

**Comment by DaelonSuzuka** [comment]
It looks like this was already solved in `master`, so the next release should fix the problem.

**Comment by theXYZT** [comment]
I just got the nightly build (as of 2025-08-03) and the bug still persists.

**Comment by DaelonSuzuka** [comment]
<img width="421" height="278" alt="Image" src="https://github.com/user-attachments/assets/89c06a08-5333-4ee0-abe8-6ce32adadabb" />

I don't know what to tell you, there's a test case for it and it passes in `master`.

**Comment by theXYZT** [comment]
Maybe I am missing something, but can you provide a link to where exactly that file is in `master`?

**Comment by DaelonSuzuka** [comment]
Poor phrasing, I think I meant that it passes in master, and also I've added a test case that proves it.
